### PR TITLE
fix: fix autocomplete; add logging and logrotate

### PR DESCRIPTION
**Pull request by trietsch**
Autocomplete wasn't working whenever no valid access token was present. This PR solves that issue, and also introduces logging to a file (in the config dir), to make issues more transparant.

### CODE REVIEW

**Review by bvdeenen — CHANGES_REQUESTED** [review]
I understand the functionality of these changes, and agree with their implementation. I do not agree with most of the chosen names. Please adhere more or less to https://golang.org/doc/effective_go#names so it don't like to see `stream.StreamNamesCompletion`

**Comment by trietsch** [comment]
> I understand the functionality of these changes, and agree with their implementation. I do not agree with most of the chosen names. Please adhere more or less to https://golang.org/doc/effective_go#names so it don't like to see `stream.StreamNamesCompletion`

Addressed, thanks for the pointer to the effective go docs.

**Review by bvdeenen — APPROVED** [review]
names ok, rest was already ok

**Pull request merged**
